export const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  ACTION_FORBIDDEN: 'ACTION_FORBIDDEN',

  SOURCE_UNAVAILABLE: 'SOURCE_UNAVAILABLE',
  SOURCE_CHANGED: 'SOURCE_CHANGED',
  SOURCE_TOO_LARGE: 'SOURCE_TOO_LARGE',

  PREVIEW_NOT_READY: 'PREVIEW_NOT_READY',
  ALREADY_RUNNING: 'ALREADY_RUNNING',
  CLEAR_IN_PROGRESS: 'CLEAR_IN_PROGRESS',
  RESULT_EXPIRED: 'RESULT_EXPIRED',

  SHEET_RANGE_NOT_SATISFIABLE: 'SHEET_RANGE_NOT_SATISFIABLE',
  WINDOW_READ_LIMIT: 'WINDOW_READ_LIMIT',

  UNSUPPORTED_FORMAT: 'UNSUPPORTED_FORMAT',
  TYPE_MISMATCH: 'TYPE_MISMATCH',

  PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
  CORRUPT_FILE: 'CORRUPT_FILE',
  INVALID_CONVERSION_OUTPUT: 'INVALID_CONVERSION_OUTPUT',
  IMAGE_CODEC_UNSUPPORTED: 'IMAGE_CODEC_UNSUPPORTED',

  RESOURCE_LIMIT_EXCEEDED: 'RESOURCE_LIMIT_EXCEEDED',
  CONVERSION_TIMEOUT: 'CONVERSION_TIMEOUT',

  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  REQUEST_IN_PROGRESS: 'REQUEST_IN_PROGRESS',

  MANIFEST_VERSION_UNSUPPORTED: 'MANIFEST_VERSION_UNSUPPORTED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  STATIC_ASSET_MISSING: 'STATIC_ASSET_MISSING',
  STATIC_ASSET_VERSION_MISMATCH: 'STATIC_ASSET_VERSION_MISMATCH',
  STYLE_BLOCKED_BY_HOST: 'STYLE_BLOCKED_BY_HOST',

  NETWORK_ERROR: 'NETWORK_ERROR',
  REQUEST_ABORTED: 'REQUEST_ABORTED',
  PROTOCOL_ERROR: 'PROTOCOL_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface PreviewErrorPayload {
  code: ErrorCode;
  message: string;
  retryable: boolean;
  requestId?: string;
  details?: Readonly<Record<string, unknown>>;
}
